### ISSUE TITLE
5.15.4 version?

### ISSUE THREAD

**Issue by moham96** [thecodemonkey86/qt_mysql_driver#16]
The current `pyqt5` version on [pypi ](https://pypi.org/project/PyQt5)is 5.15.4  can you provide a build for that verison

**Comment by thecodemonkey86** [comment]
I learned that Qt released the source code for versions up to 5.15.5, so that version is now available https://github.com/thecodemonkey86/qt_mysql_driver/releases/tag/qmysql_5.15.5
