### ISSUE TITLE
OCI Driver

### ISSUE THREAD

**Issue by vantablack-99** [thecodemonkey86/qt_mysql_driver#18]
Could you please be able to atleast try build and oci driver for windows(qt5.15.2/msvcX64) ?

I've spent much time but in the end it always ends up in an error.

I've asked in forum but it also ended up in an error.

**Comment by thecodemonkey86** [comment]
Hi, I managed to build the driver, you can try it [here](https://github.com/thecodemonkey86/qt_oci_driver/releases/tag/qoci_driver_5.15.2)

**Comment by vantablack-99** [comment]
Thanks for your reply and I'm sorry for not checking up your reply.

I'll let you know if this works fine with my machine.

Thanks again.
