### ISSUE TITLE
this is awesome

### ISSUE THREAD

**Issue by jesse996** [thecodemonkey86/qt_mysql_driver#19]
first i followed the official document ,try to build the plugin on windows,everything is fine ,but it always show ` QMYSQL driver not loaded`, even the available drivers list contains the QMYSQL.i have being doing this all day,but still don't know why.
then i found this repo,just download it,it finally works!!!
thany you so much bro

**Comment by thecodemonkey86** [comment]
Hi, I'm glad it's working for you
