### ISSUE TITLE
project file

### ISSUE THREAD

**Issue by KristianDIY** [thecodemonkey86/qt_mysql_driver#2]
Hello, in the readme it says: Unlike the original .pro file this project can be built in Qt Creator, the source code is however unchanged

But I cannot find any project file?  How can one build or include this with only the .dll availiable? 

Thanks though :)

**Comment by thecodemonkey86** [comment]
there are .pro files per Git branch for each Qt version


![image](https://user-images.githubusercontent.com/11927938/79683440-74eabe80-822a-11ea-84e7-7d00a7ab4680.png)

**Comment by KristianDIY** [comment]
aha ok! :)  I was in there trying to build my own dlls, did not go so good. 

Hmm, so the only thing i need to do for this to work, is to add your dll folders to the a source version of the qt-version i use in qt creator, than use the command prompt env that matches that build and source version then run qmake, mingw32-make etc and that's it?  

Or do i just add the dlls directly to the mingw qt sqldriver mysql folder?

Thank you very much for this :)

**Comment by thecodemonkey86** [comment]
if you just want to use the driver DLL in your project, you can create a subfolder "sqldrivers" in the Qt Creator build directory (usually where your "debug" and "release" folders are), like this:
![image](https://user-images.githubusercontent.com/11927938/79683989-4a026980-822e-11ea-945b-5acf3910504a.png) 
and copy the qsqlmysqld.dll (qsqlmysql.dll respectively) there. In addition you need libmysql.dll either in your build directory or somewhere else with a reference in your PATH variable:
![image](https://user-images.githubusercontent.com/11927938/79684040-aa91a680-822e-11ea-8db1-dbed647b202f.png)

If you want to build the driver DLL your own, you can load the sqldrivers.pro in Qt creator, build using qmake and do the same with the resulting qsqlmysql.dll as described above

**Comment by KristianDIY** [comment]
That seems to have worked! 
Before i got theese and now there is nothing, so thank you very much for your help!

QSqlDatabase: QMYSQL driver not loaded
QSqlDatabase: available drivers: QSQLITE QODBC QODBC3 QPSQL QPSQL7

I will try the build process again myself in a little while, as i need to learn, but there was 100 different methods online, and think I've already tried 20 of them... Will do as you described when I give it a shot, thanks again :)

Have a very good day! 👍

**Comment by thecodemonkey86** [comment]
I'm glad it worked
