### ISSUE TITLE
Qt5.9.9 MinGW 32bit?

### ISSUE THREAD

**Issue by jps05** [thecodemonkey86/qt_mysql_driver#20]
Can you please provide also the qt_mysql_driver for the version mentioned above?

**Comment by thecodemonkey86** [comment]
Hi, I made a release for version 5.9.9: [https://github.com/thecodemonkey86/qt_mysql_driver/releases/tag/qmysql_5.9.9](https://github.com/thecodemonkey86/qt_mysql_driver/releases/tag/qmysql_5.9.9)
