### ISSUE TITLE
Qt 6.2.3

### ISSUE THREAD

**Issue by abdullah-radwan** [thecodemonkey86/qt_mysql_driver#21]
Hi!

Can you provide a build for Qt 6.2.3? The 6.2.2 build causes a CTD. 

Regards,
Abdullah Radwan

**Comment by thecodemonkey86** [comment]
Hi, the build for 6.2.3 is [here](https://github.com/thecodemonkey86/qt_mysql_driver/releases/tag/qmysql_6.2.3)

**Comment by abdullah-radwan** [comment]
Thank you!
