### ISSUE TITLE
Could I share the Github file links?

### ISSUE THREAD

**Issue by InfinityEx** [thecodemonkey86/qt_mysql_driver#22]
It's awesome! I have tried to build the qmysql drivers too many times,I don't know why I have copy the builded driver files to mingw81_32\plugins\sqldrivers\ it still show me "Driver not loaded". Now I download your files, it worked XD. Thanks for your build! Could I share your Github file links to another website? Because I'm not sure share the links without consent is polite.

**Comment by thecodemonkey86** [comment]
hi, glad to hear it's been working for you. You certainly may link to the files

**Comment by InfinityEx** [comment]
> hi, glad to hear it's been working for you. You certainly may share the links to the files

Thanks a lot !😆 And ......  Could you please update the steps/differences of build qmysql.dll on Windows in your free time? 🥺
>>https://github.com/thecodemonkey86/qt_mysql_driver/issues/14

**Comment by InfinityEx** [comment]
> hi, glad to hear it's been working for you. You certainly may share the links to the files

Thanks a lot ！
