### ISSUE TITLE
How to use with PySide6?

### ISSUE THREAD

**Issue by Nishi** [thecodemonkey86/qt_mysql_driver#23]
I could make it work in PySide6,

did anyone succeed in accessing MariaDB databases from PySide6?

**Comment by thecodemonkey86** [comment]
Hi,
I sucessfully tested accessing MariaDB v10.7.3 from PySide6 / Qt 6.2.3. What is the error message?

**Comment by Nishi** [comment]
Qt 6.3.0 was released, so I found some time to tackle on this issue again.
Finally I succeeded at solving the "QSqlDatabase: QMARIADB driver not loaded" issue of PySide6 !

I used 64-bit Qt 6.3.0, Python 3.10.4, PySide6 6.3.0 on Windows 10.
I successfully connected PySide6 to MariaDB 10.6.5, even though as I may judge by the commit #ee8ccd7c58, it is buggy or, at least, its connector has some issues:
	https://github.com/bgallois/QMYSQL_driver_prebuilt/commit/ee8ccd7c58a39b19820044acde8bf05f00cbce06
For my tests, I downloaded pre-built SQL drivers for Qt platform from this project's [releases](https://github.com/thecodemonkey86/qt_mysql_driver/releases/tag/qmysql_6.3.0).
Also, I found automated scripts to built yourself, but I didn't use them:  https://github.com/bgallois/QMYSQL_driver_prebuilt


TROUBLESHOOTING GUIDE.

Note, here RDMS means MariaDB or MySQL.
Note, %QT_PLUGIN_PATH% is an environment variable, it can be defined by a user or even by your python script (before using PySide6).

These things are necessary to connect PySide6 and the Qt platform to MariaDB:
1. custom-built Qt DLL (a SQL driver for Qt platform):  "qsqlmysql.dll"
		Note, a pre-built debug version (named "qsqlmysql + d + .dll" = "qsqlmysqld.dll") did NOT work with PySide6 from my experience!
2. RDMS DLL (aka "client DLL"):
		I used "libmysql.dll",
		but "MariaDB/lib/libmariadb.dll" also works (it must be renamed into "libmysql.dll"!),
		or, if you have 64-bit HeidiSQL installed, any of "libmariadb.dll" / "libmysql.dll" / "libmysql-6.1.dll" works too (if renamed into "libmysql.dll");
		N.B. MariaDB distribution installed 32-bit HeidiSQL for me, thus don't copy DLLs from there, they are incompatible.
3. dependencies of the RDMS DLL:  "libcrypto-1_1-x64.dll" and "libssl-1_1-x64.dll"

Possible issues preventing Qt drivers from loading:
1.		"qsqlmysql.dll" is not located in %QT_PLUGIN_PATH%/sqldrivers
2.		the RDMS DLL is not found in %PATH% or current directory. If you place the DLL near the python script, this won't work if current working directory is different from script's location.
3.		it's dependecies are not found in %PATH% or current directory
4.		binary incompatibility - e.g. if "sqldrivers/qsqlmysql.dll" is built with MinGW or it is a pre-built debug version. N.B. it must be a release version built using MSVC
5.		architecture mismatch e.g. Qt is 64-bit, but RDMS DLL is 32-bit - it happens if RDMS DLL is copied from MariaDB installation, i.e. "C:\Program Files (x86)\Common Files\MariaDBShared\HeidiSQL\libmysql.dll".
		Ensure that everything is 64-bit: Qt, qsqlmysql.dll, libmysql.dll / libmariadb.dll, libcrypto-1_1-x64.dll", and "libssl-1_1-x64.dll.
		When troubleshooting, you can check whether DLL is 32- or 64-bit using the FileInfo.WLX plugin for Total Commander, MiTeC EXE Explorer (http://www.mitec.cz/exe.html), "dumpbin /headers some_file.dll | findstr machine" from Visual Studio, or FileAlyzer.
		More ways can be found here:  https://www.winhelponline.com/blog/find-out-if-a-program-exe-file-is-32-bit-or-64-bit/#compat


ADDITIONAL INFORMATION ON WHERE QT LOOKS UP LIBRARIES.

About locations for Qt platform driver "sqldrivers/qsqlmysql.dll":
	the DLL must be placed in "sqldrivers" sub-directory of any of following directories:
		%QT_PLUGIN_PATH%/sqldrivers/     (if defined)
		<python-install-dir>/lib/site-packages/PySide6/plugins/sqldrivers/
		<python-install-dir>/sqldrivers/

About locations for RDMS DLLs:
	All of the following files must be present in %PATH% or in a current working directory:
		libcrypto-1_1-x64.dll
		libmysql.dll
		libssl-1_1-x64.dll


MY FINAL SOLUTION.

I unpacked "qsqlmysql.dll_Qt_SQL_driver_6.3.0_MSVC2019_64-bit.zip" into "plugins" sub-directory near my python script.
I added this to my python program, and now PySide6 can work with MariaDB (even 10.6.5 version) without friction:
```
	QT_PLUGIN_PATH = os.path.join(os.path.dirname(__file__), 'plugins')
	os.environ['QT_PLUGIN_PATH'] = QT_PLUGIN_PATH
	os.environ["PATH"] += os.pathsep + QT_PLUGIN_PATH

```
Now all DLLs are being loaded from the "plugins" sub-directory! This allows to easily distribute PySide6 programs.
