### ISSUE TITLE
Where are the QMYSQL drivers trying to find MySQL?

### ISSUE THREAD

**Issue by BobSegrest** [thecodemonkey86/qt_mysql_driver#29]
I need to create a desktop GUI app that I can deploy on both Windows and Linux systems using open source / public domain tools.  The app has to read/write to MySQL database.  The best solution seems to be Python and PyQt5 or 6.  I'm trying to make Python 3.9 work with PyQt5 5.15 work on a Windows 10 system.  After 5 days I finally tripped into this site and have loaded the qsqlmysql.dll and qsqlmysqld.dll files for Qt5 into my ...Qt5\plugins\sqldrivers folder. At least now I am able to see 3 MySQL drivers when I print QSqlDatabase.drivers().  [Thank you, progress at last...]

But, I'm still getting the all consuming "Driver not loaded Driver not loaded" as my last error when I try to open the database.

I have tried this on 2 different systems, 1 with MySQL 8.1 installed and one with MariaDB 10.9.2 installed.  In each case I have tried all 3 of the drivers listed ('MIRIADB', 'MYSQL', 'MYSQL3') and get the same result.

It occurs to me that the problem might be that whatever file the QtSQL drivers are looking for, isn't where the drivers are looking.

Can anyone tell where and what to look for?

If I'm doing or overlooking something stupid, PLEASE point me in the right direction.  I really need this to work...
Bob

**Comment by thecodemonkey86** [comment]
Hi,
the following is working for me:

- I installed Qt 5.15 MSVC 2019:
![grafik](https://user-images.githubusercontent.com/11927938/190690051-59ce59ba-f4ca-495f-8363-02ba6a4dd4f3.png)

- I Installed Python 3.10 from https://www.python.org/ftp/python/3.10.7/python-3.10.7-amd64.exe (but I don't see any reason this shouldn't work on 3.9 too)
- I installed PyQt5 via `pip install PyQt5`
- I copied the entire contents of https://github.com/thecodemonkey86/qt_mysql_driver/files/5575770/qsqlmysql.dll_Qt_SQL_driver_5.15.2_MSVC2019_64-bit.zip into `C:\Users\win10\AppData\Local\Programs\Python\Python310` (just replace the user name accordingly) like this:
![grafik](https://user-images.githubusercontent.com/11927938/190691129-e471e39c-f594-4c83-b33b-9770c5892269.png)

- then a sample program prints values from a MySQL 8.0 database (should work with MariaDB too)

```
import sys
from PyQt5.QtCore import QCoreApplication
from PyQt5.QtSql import QSqlDatabase
from PyQt5.QtSql import QSqlQuery

if __name__ == "__main__":
    app = QCoreApplication(sys.argv)
    db = QSqlDatabase.addDatabase("QMYSQL")
    db.setHostName("localhost")
    db.setDatabaseName("test")
    db.setUserName("root")
    db.setPassword("7dj+vb7;dHfh6f")
    ok = db.open()
    if ok:
        q = QSqlQuery(db)
        if q.exec("select * from table1"):
            while q.next():
                print(q.value("id"))
    sys.exit(app.exec())
 
```
![grafik](https://user-images.githubusercontent.com/11927938/190691771-721b04a9-60e2-47d8-945b-cd6085b30f9d.png)

hope this helps. You could also try setting the environment variable QT_DEBUG_PLUGINS=1 in Qt Creator (projects section):
![grafik](https://user-images.githubusercontent.com/11927938/190692238-02234485-493f-4311-8c2c-debb6e3a06bb.png), which could provide some hints for plugin loading errors during startup

**Comment by BobSegrest** [comment]
Thank you very much for your response!

Can you elaborate/clarify your very first step ("I installed Qt 5.15.2 MSVC 2019:") for me please.  I may have missed something critical here and the rest of the steps are at least familiar.

What exactly what did you install (something from Qt.io...)?

Where did you get the installation kit?

Bob

**Comment by thecodemonkey86** [comment]
it's the official, open source version of Qt I used, downloaded from official website qt.io, https://d13lb3tujbc8s0.cloudfront.net/onlineinstallers/qt-unified-windows-x64-4.4.1-online.exe, I only checked Qt 5.15.2 MSVC 2019 64-bit and left everything else as pre-selected by default in Qt Maintenance Tool (=installer)

**Comment by BobSegrest** [comment]
Ok, that may be what I missed.  Let me work it and I will let you know what happens either way.

Bob

**Comment by BobSegrest** [comment]
Thank you very very much!!!

With the hindsight of success, I had missed 2 critically important points.

#1 You have to install the kit from Qt.io.  I had played with this earlier, but abandoned it and started over when it wouldn't connect to MySQL.  I reinforced my misunderstanding of the problem further, by using pip to install PyQy5-tools which gave me a functional QtDesigner.  It may also be worth mentioning that PyQt5-tools do not install correctly (at least on Windows 10) with Python 3.10.  This is the only reason I reverted back to Python 3.9

#2 It was not clear, and I inserted the [qsqlmysql.dll_Qt_SQL_driver_5.15.2_MSVC2019_64-bit.zip] files into the wrong folder. [...AppData\Local\Programs\Python\Python39\Lib\site-packages\PyQt5\Qt5\plugins\sqldrivers]  I will suggest the correct path be added to the ReadMe for at least Windows users...

After reading your last clarification, I tried just installing the Qt.io kit on my existing development VM without any change in the result. So I built a new Windows 10 system from scratch and installed the same tools, in the sequence you provided.  The only addition I made, was installing the MySQL 8.0 kit right after I installed Python 3.10 from the link you provided (rather than the Microsoft Store kit).

I ran a slightly modified version of the sample python code you provided, and everything worked.  I installed VS Code, pulled in my own project fragments and the problem is solved.

Thank you, Thank You, THANK YOU!

**Comment by thecodemonkey86** [comment]
great to hear it's solved

**Comment by Murkyshadow** [comment]
It is WORK. Thank you
