### ISSUE TITLE
parameter count mismatch

### ISSUE THREAD

**Issue by CppProgrammer23** [thecodemonkey86/qt_mysql_driver#3]
I've seen your readme.md file but my driver is loaded successfully, I have a problem with "Parameter count mismatch". when I try to connect to my database, it's ok, but when I want to send data it shows that error I use PHPMyAdmin, you can find my project under:  [https://github.com/CppProgrammer23/QtProjects/tree/master/QMachine_Check_Up](url)

**Comment by thecodemonkey86** [comment]
Hi,
`db = QSqlDatabase::addDatabase("QSQLITE");`
you are loading the SQLite driver, not the MySql driver

**Comment by CppProgrammer23** [comment]
hi there,
MySql doesn't work, it shows me failed if I set it to MySql

**Comment by thecodemonkey86** [comment]
i'm gonna need more information
- which Qt version
- which compiler
- which MySQL version
- which files from my releases
- exact error output and in what file and line your source code it occurs

**Comment by CppProgrammer23** [comment]
I'm using Qt 5.14.2, I use the C++17 compiler (MSVC2017), I use phpMyAdmin because I don't want to install Sql on my computer. The error is when I prepare the Query to send data to the db. The program execute line 161 instead of line 159 which shows me the error "Parameter count mismatch"

**Comment by thecodemonkey86** [comment]
you should first check if qsr.prepare(...) returns true and if it returns false, show what qsr.lastError().text() says in that case

**Comment by CppProgrammer23** [comment]
yes it returns false, the message is : "Parameter count mismatch"

**Comment by thecodemonkey86** [comment]
some more things to test
- does a simple select query "select * from ..." with/without parameters work
- do ?-parameters work, like "INSERT INTO mytab (operator_id, machine_id) VALUES (?, ?)", then addBindValue instead of bindValue

**Comment by CppProgrammer23** [comment]
it doesn't work; neither select nor create , also I tried "INSERT INTO mytab (operator_id, machine_id) VALUES (?, ?)" and same error

**Comment by thecodemonkey86** [comment]
what is the error message if you don't use any parameters at all, i.e. select all rows

**Comment by CppProgrammer23** [comment]
"no query unable to fetch row"

**Comment by thecodemonkey86** [comment]
if it's not too much to ask and your database doesn't contain any confidential information: could I get temporary read only access to it for further analysis?

**Comment by CppProgrammer23** [comment]
yes of course: check this: [https://github.com/CppProgrammer23/QtProjects/blob/master/QMachine_Check_Up/Readme.md](url)

**Comment by thecodemonkey86** [comment]
the server doesn't accept connections from my IP address

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird?

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird?

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by CppProgrammer23** [comment]
I think there’s a problem with that database? It’s weird? My server is set on UK, Ireland server

**Comment by thecodemonkey86** [comment]
probably database user privileges must be se accordingly. See [https://dev.mysql.com/doc/refman/8.0/en/grant.html](https://dev.mysql.com/doc/refman/8.0/en/grant.html)

**Comment by thecodemonkey86** [comment]
seems to be abandoned and not really related to the driver anyway. Closin

**Comment by Amarenko-prog** [comment]
Hello I am getting error "Failed to create account. Parameter cont mismatch", can somebody help me here is my code: https://github.com/nttminh/ticket-booking-dashboard

**Comment by thecodemonkey86** [comment]
Hi, probably not, unless you provide more information and  post code here and as [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)

    which Qt version
    which compiler
    which MySQL version
    which files from my releases
