### ISSUE TITLE
Any shot of getting a release for 5.15.7

### ISSUE THREAD

**Issue by tajetaje** [thecodemonkey86/qt_mysql_driver#31]
I am trying to get MySQL support for KMyMoney, but it doesn't have the needed DLL, I'd compile it myself but don't have to storage to install everything.

**Comment by thecodemonkey86** [comment]
Hi, I'm going to provide this release, but it'll take some time to build Qt from source

**Comment by thecodemonkey86** [comment]
MSVC 2019 64 bit release is ready:
https://github.com/thecodemonkey86/qt_mysql_driver/releases/tag/qmysql_5.15.7

**Comment by tajetaje** [comment]
Awesome, thank you! Very helpful
