### ISSUE TITLE
the version of the sqldrivers in "qsqlmysql.dll driver 5.13.2 + libmysql MySQL 8.0"  is actually 5.14.2 !

### ISSUE THREAD

**Issue by ccoob** [thecodemonkey86/qt_mysql_driver#35]

**Comment by ccoob** [comment]
Someone who faces problems can repalce the sqldrivers with another assert "qsqlmysql.dll driver 5.14.2".

Remember to rename the debug driver from "qsqlmysql.dll" to "qsqlmysqld.dll". The name of the debug and release driver is  same in "qsqlmysql.dll driver 5.14.2", maybe the author forgot to change it.

**Comment by ccoob** [comment]
the sqldrivers in "qsqlmysql.dll driver 5.14.2" are actually 5.13.2.

**Comment by thecodemonkey86** [comment]
Could you please clarify which files are incorrect and post the link(s) here. Your last post and the issue title don't match. Thank you very much

**Comment by ccoob** [comment]
[](https://github.com/thecodemonkey86/qt_mysql_driver/files/5322151/qsqlmysql.dll_Qt_SQL_driver_5.13.2_MinGW_7.3_64-Bit.zip
)
the drivers in the folder "sqldrivers" are for Qt 5.14.2 and the file "libmysql.dll" is for Qt 5.13.2. When  you try to use both of them, it reports a error like "Cannot mix incompatible Qt library (version 0x50d02) with this library (version 0x50e02)" 


[](https://github.com/thecodemonkey86/qt_mysql_driver/files/4460982/qsqlmysql.dll_Qt_SQL_driver_5.14.2_MinGW_64-Bit.zip)
And the drivers in this link are for Qt 5.13.2 while the title is "5.14.2".
I don't know the version of the "libmysql.dll" in this link.     But it can't be for MySQL 8.0.

**Comment by thecodemonkey86** [comment]
As you can see in the following screenshots, the versions of the drivers are correct:
![grafik](https://github.com/thecodemonkey86/qt_mysql_driver/assets/11927938/c1c91a4a-26e5-4aed-bbf4-9dc931a0cf94)

![grafik](https://github.com/thecodemonkey86/qt_mysql_driver/assets/11927938/d71754aa-6cac-404d-8b95-8f016d3170c8)


![grafik](https://github.com/thecodemonkey86/qt_mysql_driver/assets/11927938/f8cfb1a5-2704-4cd2-9c25-689a40fdd046)


I admit that the libmysql.dll in the 5.14.2 package is very old. Please use a newer one that comes with a current MySQL installation

**Comment by ccoob** [comment]
**Sorry,it is my bad**. 
I didn't know how to see the version of the library. At first I downloaded the 5.14.2 package and it didn't work (I didn't know the libmysql.dll is too old). And then I downloaded the 5.13.2 package and it still didn't work(because the driver version was not fit). 
Finally I mixed them up, and it  miraculously  succeeded. I  thought it was the drivers fault, but actually it wasn't.
Could you please delete this issue? It is a disgrace.
**Sorry for wasting your time**.
