### ISSUE TITLE
Any shot of getting a release for 5.12.12

### ISSUE THREAD

**Issue by melinaaraa** [thecodemonkey86/qt_mysql_driver#43]
Hi
I am trying to use MySQL in my qt application, but it doesn't have the needed DLL, I tried to compile it myself but i couldn't do it

**Comment by thecodemonkey86** [comment]
Hi, I currently only got the MSVC 2017 64 Bit version finished
https://github.com/thecodemonkey86/qt_mysql_driver/releases/tag/qmysql_5.12.12

**Comment by austinkottke** [comment]
Do you have an OSX build? 5.15

**Comment by thecodemonkey86** [comment]
@austinkottke I don't have the equipment to build for OSX, so no

**Comment by thecodemonkey86** [comment]
all builds for 5.12.12 I'm making are now online
