### ISSUE TITLE
Any chance of V5.12.3?

### ISSUE THREAD

**Issue by taranakiretreat** [thecodemonkey86/qt_mysql_driver#7]
Kia ora @thecodemonkey86
Thank you SO much for providing this. Seriously! I have to admit it's stumped me; I just need to make my application cross-platform, but don't know where to START with compiling in Windows and never want to.
For complicated reasons, I have to use Anaconda for this particular application, and the most recent pyqt version available is 5.12.3 - I'm wondering if there is any chance you might be prepared to compile and release that version? I am using mysql-connector-python 8.0.22
Yours very hopefully, Jamie

**Comment by thecodemonkey86** [comment]
Hi,
sorry this took a while. Here is the release for 5.12.3

https://github.com/thecodemonkey86/qt_mysql_driver/releases/tag/qmysql_5.12.3

**Comment by taranakiretreat** [comment]
Ohhh you extremely kind person!! Thank you so very very much indeed for doing this. This sort of kindness goes a very, very long way. Much respect and appreciation from our team in New Zealand. Jamie
